# Generated by Django 5.1.6 on 2025-03-02 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='date_limite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
