# Generated by Django 5.1.6 on 2025-03-02 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0004_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('task', 'Tâche'), ('project', 'Projet'), ('other', 'Autre')], default='other', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
