# Generated by Django 5.1.6 on 2025-03-08 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0005_notification_type_alter_notification_date_creation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
