# Generated by Django 5.1.6 on 2025-03-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taches', '0007_alter_tache_assigne_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='tache',
            name='date_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
