# Generated by Django 5.1.6 on 2025-03-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='heure_notification',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='recevoir_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='types_notifications',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
