# Generated by Django 5.1.6 on 2025-02-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='date_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Terminé', 'Terminé'), ('En attente', 'En attente')], default='En cours', max_length=50),
        ),
        migrations.AlterField(
            model_name='projet',
            name='description',
            field=models.TextField(blank=True, default='Aucune description'),
        ),
        migrations.AlterField(
            model_name='projet',
            name='titre',
            field=models.CharField(max_length=255),
        ),
    ]
