# Generated by Django 5.1.6 on 2025-03-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0005_remove_projet_theme_couleur_alter_projet_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='progression',
            field=models.FloatField(default=0.0),
        ),
    ]
