# Generated by Django 5.1.6 on 2025-03-15 08:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projets', '0006_projet_progression'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='membres',
            field=models.ManyToManyField(blank=True, related_name='projets_membre', to=settings.AUTH_USER_MODEL),
        ),
    ]
