# Generated by Django 5.1.6 on 2025-03-09 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_projets', models.PositiveIntegerField(default=0)),
                ('projets_en_cours', models.PositiveIntegerField(default=0)),
                ('taches_en_attente', models.PositiveIntegerField(default=0)),
                ('taches_retard', models.PositiveIntegerField(default=0)),
                ('progression_projets', models.FloatField(default=0.0)),
                ('evolution_taches', models.JSONField(default=dict)),
                ('dernier_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistique', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
