# Generated by Django 5.1.6 on 2025-03-09 01:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistiques', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistique',
            name='evolution_taches',
        ),
        migrations.AlterField(
            model_name='statistique',
            name='projets_en_cours',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='taches_en_attente',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='taches_retard',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='total_projets',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='statistique',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistiques', to=settings.AUTH_USER_MODEL),
        ),
    ]
